### ISSUE TITLE
Question about the achievement of ConstP in file ”DP_QEq_ConstP.py“ 

### ISSUE THREAD

**Issue by Ternity** [sxu39/DP-QEq#2]
Dear developers:
What an amazing work! It inspires me a lot.
However, I have a question about the implementation of ConstP in file ”DP_QEq_ConstP.py“ :
In line [428 to 452](https://github.com/sxu39/DP-QEq/blob/c7484c290f817d05c48cb7fe4bbe0817597b7bf0/DP_QEq_ConstP.py#L428-L452), two functions (`fn_value_and_proj_grad` and `solve_q_pg`)  are defined to iterative optimization of charges. But it appears that you're using a gradient projection method (function `value_and_proj_grad`) as a constraint on the total charge to optimize Qeq energy (`get_Energy_Qeq_2`), which seems more like a ConstQ optimization. Additionally, in the defined ASE calculator (`DPQEQ`), the electric potential is initialized but not utilized in any operations.<br>
Therefore, in DP-QEq, is the implementation of ConstP still based on the minimization of giant canonical energy ($\Omega=E_{QEq}-\sum_{i}^{N}\phi_i Q_i$)? <br>
Thank you again for your outstanding work, I am looking forward to your reply, and wish you a good day!

Best regards,
Ternity

**Comment by sxu39** [comment]
Dear Qinghan:




Thanks for your interest in our work and this good question! Yes, the ConstP implementation is also performed under a neutrality constraint. We actually did not apply the Q_tot = 0 constraint in our original version and added a non-neutrality correction term in the QEq energy calculation, but a reviewer brought up a concern about this treatment and asked us to add this constraint. We find that there is negligible difference between these two setups (no Q_tot constraint + a non-neutrality correction vs. a neutrality constraint), because even we had a total net charge in the periodic cell in our earlier version, the net charge value is extremely small (0.16 |e| for the whole cell containing ~3000 atoms). We do not want argue with the reviewer about this minor issue, so we decide to implement the neutrality constraint in the current version. For your second question, once the applied bias potential is setup at the beginning of a ConstP run, the mathematically equivalent effect is counter shifting the electro negativities of Li atoms in different electrode sides (a positive/negative shift in the cathode/anode side). You can also find the details in our manuscript uploaded on arXiv. 




I also forward our communications to the first author of this work, Taiping Hu, who is a postdoc in my group and leads this project. We can have more discussion by email if you have other questions. Thank you again for your question and interest!




Best regards,

Shenzhen







-----Original Messages-----
From:"Qinghan Yu" ***@***.***>
Send time:Saturday, 10/12/2024 18:32:26
To: sxu39/DP-QEq ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sxu39/DP-QEq] Question about the achievement of ConstP in file ”DP_QEq_ConstP.py“ (Issue #2)






Dear developers:
What an amazing work! It inspires me a lot.
However, I have a question about the implementation of ConstP in file ”DP_QEq_ConstP.py“ :
In line 428 to 452, two functions (fn_value_and_proj_grad and solve_q_pg) are defined to iterative optimization of charges. But it appears that you're using a gradient projection method (function value_and_proj_grad) as a constraint on the total charge to optimize Qeq energy (get_Energy_Qeq_2), which seems more like a ConstQ optimization. Additionally, in the defined ASE calculator (DPQEQ), the electric potential is initialized but not utilized in any operations.

Therefore, in DP-QEq, is the implementation of ConstP still based on the minimization of giant canonical energy ($\Omega=E_{QEq}-\sum_{i}^{N}\phi_i Q_i$)?

Thank you again for your outstanding work, I am looking forward to your reply, and wish you a good day!

Best regards,
Ternity

**Comment by taipinghu** [comment]
> Dear developers: What an amazing work! It inspires me a lot. However, I have a question about the implementation of ConstP in file ”DP_QEq_ConstP.py“ : In line [428 to 452](https://github.com/sxu39/DP-QEq/blob/c7484c290f817d05c48cb7fe4bbe0817597b7bf0/DP_QEq_ConstP.py#L428-L452), two functions (`fn_value_and_proj_grad` and `solve_q_pg`) are defined to iterative optimization of charges. But it appears that you're using a gradient projection method (function `value_and_proj_grad`) as a constraint on the total charge to optimize Qeq energy (`get_Energy_Qeq_2`), which seems more like a ConstQ optimization. Additionally, in the defined ASE calculator (`DPQEQ`), the electric potential is initialized but not utilized in any operations. Therefore, in DP-QEq, is the implementation of ConstP still based on the minimization of giant canonical energy ( Ω = E Q E q − ∑ i N ϕ i Q i )? Thank you again for your outstanding work, I am looking forward to your reply, and wish you a good day!
> 
> Best regards, Ternity

Dear Qinghan,

Thanks for your attention to our work. The implementation of the DP-QEq under the ConstP condition has been updated in our new version, as anwsered by Shenzhen.

for you second question, you can find the code shown in this line https://github.com/sxu39/DP-QEq/blob/c7484c290f817d05c48cb7fe4bbe0817597b7bf0/DP_QEq_ConstP.py#L795  about the details in the ASE. 
The returned \chi values are different in the ConstQ and ConstP condition.

**Comment by Ternity** [comment]
Dear Shenzhen and Taiping,
<br>
Thank you very much for your reply. Indeed, the non-zero net charge of a PBC system may lead to some potential issues,  particularly when addressing electrostatic effects using PME. Additionally, after studing the derivation of the linear equation system involving  Hessian matrix, charge, electronegativity and additional potential in the paper,  I have gained a clear understanding of the implementation method for the additional potential.
Thank you again for your reply!
<br>
Best regards,
Qinghan

<details>
  <summary> @taipinghu reply</summary>
Dear Qinghan,
<br>
Thanks for your attention to our work. The implementation of the DP-QEq under the ConstP condition has been updated in our new version, as anwsered by Shenzhen.  
 
for you second question, you can find the code shown in this line
 https://github.com/sxu39/DP-QEq/blob/c7484c290f817d05c48cb7fe4bbe0817597b7bf0/DP_QEq_ConstP.py#L795
about the details in the ASE.
The returned \chi values are different in the ConstQ and ConstP condition. </details>
